### ISSUE TITLE
viewflow-example: not all buttons seen

### ISSUE THREAD

**Issue by tilusnet** [pakerfeldt/android-viewflow#2] opened 2011-05-08 18:34 UTC
Hi! I was curious about your library, so I tried it on my device (HTC Desire, Froyo OS) by running the viewflow-example:
on your screenshot all buttons from 0 to 9 are shown, whereas on mine only 0 to 6.
I am going to make a screenshot for you.

tilusnet

**Comment by tilusnet** [comment] 2011-05-08 18:36
Screenshot:
http://tilusnet.com/tmp/gfx/viewflow-example-notallseen.png

**Comment by pakerfeldt** [comment] 2011-05-08 18:41
Alright, so there is something odd with the main.xml layout in the example. The buttons are only for convenience though and shouldn't effect the actual library. 
What if you flip orientation?

**Comment by tilusnet** [comment] 2011-05-08 18:47
True, it's not related to the library, I just thought I let you know. (although the app crashed the first time I flicked beyond number 9, but never since)
In landscape orientation there's enough space for all buttons.

**Comment by pakerfeldt** [comment] 2011-05-08 18:50
Yes, thanks for the report. I will try to have this fixed in the future.

The crash experience is interesting as well. If you ever manage to reproduce the FC, please report it. I'm very keen on making the library stable.

**Comment by pakerfeldt** [comment] 2011-05-11 21:09
Closing this since I've just merged the pull request from Eric that introduces a new kind of nice flow indicator.

**Closed as completed by pakerfeldt** 2011-05-11 21:09 UTC
